version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - dockerfile: Dockerfile-goreleaser
    image_templates:
      - "quay.io/lunarway/humio_exporter:latest"
      - "quay.io/lunarway/humio_exporter:v{{ .Major }}"
      - "quay.io/lunarway/humio_exporter:v{{ .Major }}.{{ .Minor }}"
      - "quay.io/lunarway/humio_exporter:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

archives:
  - id: archives
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"

changelog:
  disable: true
