FROM alpine:3.22.2 as builder

RUN apk update
RUN apk add ca-certificates

FROM scratch

ENTRYPOINT [ "/humio_exporter" ]
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY humio_exporter /